### PR TITLE
Use Settings instead of Configuration

### PR DESCRIPTION
**Pull request by scharf**
Explain where to change the `configuration`, which actually is a `setting`.

### CODE REVIEW

**Comment by egamma** [comment]
Hi michael @scharf :smile: 

The wording makes it more accurate. One issue I've see is that users are putting eslint rules into the settings instead of into an eslintrc config file. I therefore suggest to also improve the wording for

From:
>`eslint.options`: an option bag as defined by the ESLint API [here](http://eslint.org/docs/developer-guide/nodejs-api#cliengine). Defaults to an empty option bag. 

To: 
>`eslint.options`: options to configure how eslint is started using the ESLint [CLI Engine API](http://eslint.org/docs/developer-guide/nodejs-api#cliengine). Defaults to an empty option bag.

**Comment by scharf** [comment]
Hi Erich,

I updated the PR with your suggestion.

**Comment by egamma** [comment]
:+1:

**Comment by dbaeumer** [comment]
Thanks @scharf :-)

**Pull request merged**
