### PR TITLE
eslintignore comment syntax highlighting

### PR DESCRIPTION
**Pull request by Hirse**
Colors comments and enables commenting of lines using keyboard shortcut.

see #459

### CODE REVIEW

**Comment by dbaeumer** [comment]
@aeschli can you please have a quick review. You know a lot more about this than I do.

**Comment by aeschli** [comment]
The change looks good!

@Hirse If you wanted you could make a similar addition for `gitignore` files as we don't have any colorization there as well.
We could share the grammar of the two, if we're sure that the syntaxes are identical.

**Comment by Hirse** [comment]
@aeschli Do you mean in vscode? 
If we add that, would it make sense to define some kind of generic `ignore-file` language for `gitignore`, `eslintignore`, `npmignore`, and possibly others?

**Comment by aeschli** [comment]
@Hirse A generic ignore-file language makes sense. We could still place it along with the git extension

**Comment by dbaeumer** [comment]
That makes sense to me as well. That would mean for eslint we would then simply reference the genernal syntax.

**Comment by Hirse** [comment]
@aeschli do you mean adding a definition in [vscode `extensions/git/languages`](https://github.com/Microsoft/vscode/tree/master/extensions/git/languages) or adding a new `ignore` extension which only contains this language definition?

**Comment by aeschli** [comment]
@Hirse I'd suggest to add it to vscode/extensions/git

**Comment by dbaeumer** [comment]
@aeschli do you recommend that we wait with this in ESLint and then reuse the one that goes into git?

**Comment by Hirse** [comment]
@dbaeumer Sorry for the delay, I have changed the code to reference the existing `ignore` language as @aeschli did in https://github.com/Microsoft/vscode/commit/eb2b51aeb9cb76d1a1ff24b015c38e5bcb90cc95 so this should be good to go now.

**Comment by dbaeumer** [comment]
Thanks!.

**Pull request merged**
