### PR TITLE
disable-eslint fixes and improvements

### PR DESCRIPTION
**Pull request by loune**
* Fix issue with 'Fix all rule' quick action not appearing (mentioned in [comment of #530](https://github.com/Microsoft/vscode-eslint/pull/530#issuecomment-439315219))
* Add setting eslint.suppressCodeActionComment with options `sameLine` or `newLine` (#573)
* Add setting eslint.showSuppressCodeAction [comment of #530](https://github.com/Microsoft/vscode-eslint/pull/530#issuecomment-436269570)
* Add setting eslint.showDocumentationCodeAction [comment of #530](https://github.com/Microsoft/vscode-eslint/pull/530#issuecomment-436269570)

### CODE REVIEW

**Comment by dbaeumer** [comment]
@loune thanks for the PR. See my comments in the review.

**Comment by loune** [comment]
@dbaeumer Changes have been made. Cheers

**Comment by dbaeumer** [comment]
@loune thanks. I merged it in and did some minor polish in regards to naming.

```
	"eslint.codeAction.showDocumentation": {
		"enable": false
	},
	"eslint.codeAction.disableRuleComment": {
		"enable": true,
		"location": "separateLine"
	}
```

Called it disable instead of suppress since ESLint itself uses disable.

**Comment by dbaeumer** [comment]
I also improved the ordering of the actions.

**Comment by loune** [comment]
Thanks @dbaeumer

**Pull request merged**
