### PR TITLE
refactor(server): Improve `_globalPaths` type

### PR DESCRIPTION
**Pull request by ExE-Boss**
Final cleanup of&nbsp;https://github.com/Microsoft/vscode-eslint/pull/572

### CODE REVIEW

**Comment by dbaeumer** [comment]
@ExE-Boss support for pnpm got added and is available in the latest version. Anything missing ?

**Comment by dbaeumer** [comment]
See https://github.com/Microsoft/vscode-eslint/pull/572

**Comment by ExE-Boss** [comment]
This PR&nbsp;improves the&nbsp;type used for&nbsp;the&nbsp;internal `_globalPaths` variable.

**Comment by ExE-Boss** [comment]
@dbaeumer Can we get this merged?

**Pull request closed without merging**
